export const SETWINDOWCONFIG = 'SET_WINDOWCONFIG'

export const SETFORMLISTS = 'SET_FORMLISTS'

export const SETCURRENTFORMCONFIG = 'SET_CURRENTFORMCONFIG'

export const SETCURRENTFORM = 'SET_CURRENTFORM'

export const SETPROJECTINFO = 'SET_PROJECTINFO'
