export const SETPROJECTINFO = 'SET_PROJECTINFO'

export const SETCURRENTMESSAGE = 'SET_CURRENTMESSAGE'

export const SETFORMSTATUS = 'SET_FORM_STATUS'

export const SETROUTERPARAMS = 'SET_ROUTER_PARAMS'
// 管理门户
export const MANAGEPORTALRIGHT = "MANAGE_PORTAL_RIGHT"

// 项目门户
export const PROJECTPORTALRIGHT = 'PROJECT_PORTAL_RIGHT'

// token失效
export const TOKENFAILURE = 'TOKENFAILURE'

export const SETMAINFORMdATA = 'SETMAINFORMdATA'
