export const SETPROJECTINFO = 'SET_PROJECTINFO'

export const SETCURRENTMESSAGE = 'SET_CURRENTMESSAGE'

export const SETFORMSTATUS = 'SET_FORM_STATUS'

export const SETROUTERPARAMS = 'SET_ROUTER_PARAMS'
